spring.application.name=SP_3_MVC_DB_LeaveManagementSystem_2

spring.datasource.url=jdbc:mysql://localhost:3306/Leave_MGMT_System?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=3141@MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
