spring.application.name=SP_3_MVC_DB_LeaveManagementSystem_2
spring.datasource.url=jdbc:mysql://localhost3306/leave_Management_System?createDatabaseIfNotExxist=true
spring.datasource.username=root
spring.datasource.password=3141@MySQL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false